export { default as Button } from './button'
export { default as DingAuth } from './dingAuth'
export { default as Switch } from './switch'
export { default as Icon } from './icon'
export { default as Spin } from './spin'
export { default as Alert } from './alert'
